// INDICATOR: `array.slice()`
// Extracted from Pine Script documentation

//@version=6  
strategy("`array.slice()`", overlay=true)  
a = array.new<float>(0)  
array.push(a, 0)  
array.push(a, 1)  
array.push(a, 2)  
array.push(a, 3)  
if barstate.islast  
    // Create a shadow of elements at index 1 and 2 from array `a`.  
    sliceOfA = array.slice(a, 0, 3)  
    label.new(bar_index, 0, "BEFORE\na: " + str.tostring(a) + "\nsliceOfA: " + str.tostring(sliceOfA))  
    // Remove first element of parent array `a`.  
    array.remove(a, 0)  
    // Add a new element at the end of the shallow copy, thus also affecting the original array `a`.  
    array.push(sliceOfA, 4)  
    label.new(bar_index, 0, "AFTER\na: " + str.tostring(a) + "\nsliceOfA: " + str.tostring(sliceOfA), style = label.style_label_up)

// ==================== Strategy Entry/Exit Logic ====================
longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if (longCondition)
    strategy.entry("Long", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("Short", strategy.short)