// INDICATOR: Session backgrounds
// Extracted from Pine Script documentation

//@version=6  
strategy("Session backgrounds", overlay = true)  
  
// Default color constants using tranparency of 25.  
BLUE_COLOR   = #0050FF40  
PURPLE_COLOR = #0000FF40  
PINK_COLOR   = #5000FF40  
NO_COLOR     = color(na)  
  
// Allow user to change the colors.  
preMarketColor  = input.color(BLUE_COLOR, "Pre-market")  
regSessionColor = input.color(PURPLE_COLOR, "Pre-market")  
postMarketColor = input.color(PINK_COLOR, "Pre-market")  
  
// Function returns `true` when the bar's time is   
timeInRange(tf, session) =>   
    time(tf, session) != 0  
  
// Function prints a message at the bottom-right of the chart.  
f_print(_text) =>   
    var table _t = table.new(position.bottom_right, 1, 1)  
    table.cell(_t, 0, 0, _text, bgcolor = color.yellow)  
  
var chartIs30MinOrLess = timeframe.isseconds or (timeframe.isintraday and timeframe.multiplier <=30)  
sessionColor = if chartIs30MinOrLess  
    switch  
        timeInRange(timeframe.period, "0400-0930") => preMarketColor  
        timeInRange(timeframe.period, "0930-1600") => regSessionColor  
        timeInRange(timeframe.period, "1600-2000") => postMarketColor  
        => NO_COLOR  
else  
    f_print("No background is displayed.\nChart timeframe must be <= 30min.")  
    NO_COLOR  
  
bgcolor(sessionColor)

// ==================== Strategy Entry/Exit Logic ====================
longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if (longCondition)
    strategy.entry("Long", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("Short", strategy.short)