// //@version=6
// strategy("request.security_lower_tf() Example", overlay=true, fill_orders_on_standard_ohlc = true)

// // ==================== Original Indicator Logic ====================

// // If the current chart timeframe is set to 120 minutes, then the `arrayClose` array will contain two 'close' values from the 60 minute timeframe for each bar.
// arrClose = request.security_lower_tf(syminfo.tickerid, "60", close)

// if bar_index == last_bar_index - 1
//     label.new(bar_index, high, str.tostring(arrClose))

// // ==================== Strategy Entry/Exit Logic ====================
// longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
// if (longCondition)
//     strategy.entry("Long", strategy.long)

// shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
// if (shortCondition)
//     strategy.entry("Short", strategy.short)
