// //@version=6
// //@description A library with custom functions.
// library("CustomFunctions", overlay = true)

// //@function         Calculates the length values for a ribbon of four EMAs by multiplying the baseLength.
// //@param baseLength The initial EMA length. Requires "simple int" because you can't use "series int" in ta.ema().
// //@returns          A tuple of length values.
// export ribbonLengths(simple int baseLength) =>
//     simple int length1 = baseLength
//     simple int length2 = baseLength * 2
//     simple int length3 = baseLength * 3
//     simple int length4 = baseLength * 4
//     [length1, length2, length3, length4]

// // Get a tuple of "simple int" length values.
// [len1, len2, len3, len4] = ribbonLengths(14)

// // Plot four EMAs using the values from the tuple.
// plot(ta.ema(close, len1), "EMA 1", color = color.red)
// plot(ta.ema(close, len2), "EMA 1", color = color.orange)
// plot(ta.ema(close, len3), "EMA 1", color = color.green)
// plot(ta.ema(close, len4), "EMA 1", color = color.blue)