//@version=6
strategy("line", overlay=true, fill_orders_on_standard_ohlc = true)

// ==================== Original Indicator Logic ====================
// Empty `line1` line ID.
var line line1 = na
// `line` type is unnecessary because line.new() returns "line" type.
var line2 = line.new(na, na, na, na)
line3 = line.new(bar_index - 1, high, bar_index, high, extend = extend.right)

// ==================== Strategy Entry/Exit Logic ====================
longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if (longCondition)
    strategy.entry("Long", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("Short", strategy.short)
