//@version=6
strategy("can", overlay=true, fill_orders_on_standard_ohlc = true)

// ==================== Original Indicator Logic ====================
//@variable A variable declared as "simple float" with a value of 5.0.
simple float myVar = 5.0

// This reassignment causes an error.
// The close variable returns a "series float" value. Since myVar is restricted to "simple" values, it cannot
// change its qualifier to "series".
myVar := close

plot(myVar)

// ==================== Strategy Entry/Exit Logic ====================
longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if (longCondition)
    strategy.entry("Long", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("Short", strategy.short)
