// //@version=6
// //@description A library with custom functions.
// library("CustomFunctions", overlay = true)

// //@function Finds the highest `source` value over `length` bars, filtered by the `cond` condition.
// export conditionalHighest(series float source, series bool cond, series int length) =>
//     //@variable The highest `source` value from when the `cond` was `true` over `length` bars.
//     series float result = na
//     // Loop to find the highest value.
//     for i = 0 to length - 1
//         if cond[i]
//             value   = source[i]
//             result := math.max(nz(result, value), value)
//     // Return the `result`.
//     result

// //@variable Is `true` once every five bars.
// series bool condition = bar_index % 5 == 0

// //@variable The highest close value from every fifth bar over the last 100 bars.
// series float hiValue = conditionalHighest(close, condition, 100)

// plot(hiValue)
// bgcolor(condition ? color.new(color.teal, 80) : na)