//@version=6
strategy("series variable not allowed", overlay=true, fill_orders_on_standard_ohlc = true)

// ==================== Original Indicator Logic ====================
//@variable A variable declared as "series int" with a value of 5.
series int myVar = 5

// This call causes an error.
// The histbase accepts "input int/float". It can't accept the stronger "series int" qualified type.
plot(close, style = plot.style_histogram, histbase = myVar)

// ==================== Strategy Entry/Exit Logic ====================
longCondition = ta.crossover(ta.sma(close, 14), ta.sma(close, 28))
if (longCondition)
    strategy.entry("Long", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("Short", strategy.short)
