"""The l2c backstop threshold must be NEGATIVE — asserted on the GENERATED .py.

WHY THIS READS THE BUILD ARTIFACT AND NOT THE .pine. On 2026-09-18 the backstop was
written in Pine as ``-(slPct + 0.25)``, intending -0.30 at sl 0.05. pine2pyne DROPPED
the parentheses and generated ``-slPct + 0.25``, which is **+0.20**. The backstop test is
``openPnlPct < DOUBLE_CHECK_PCT``, so a positive threshold inverts it: it fires on the
first bar of every position, cancels the bracket and flattens — destroying the measurement
it exists to protect and placing orders nobody asked for, on a live account.

A second spelling, ``0.0 - (slPct + 0.25)``, generated ``0.0 - slPct + 0.25`` and was ALSO
+0.20. The shipped form is ``-0.25 - slPct``, which has no parentheses to drop.

So the Pine source is not the thing to assert on: the ``.py`` is what runs, and the two
silently disagree until the next transpile (CLAUDE.md, "the .py is a build artifact"). A
pin reading the ``.pine`` would have passed against every one of the broken builds.

WHAT IS PINNED IS THE SIGN, NOT THE VALUE. The magnitude is a tuning decision — it changed
from ``-3 * max(tp, sl)`` to ``-(sl + 0.25)`` during review and may change again. The sign
is a safety property: a loss-side backstop whose threshold is positive is not a loose
backstop, it is an inverted one.

Run explicitly: ``pytest plugins/dnse/tests/test_l2c_backstop_sign.py -q``.
"""
from __future__ import annotations

import pathlib
import re

import pytest

VEHICLE = (pathlib.Path(__file__).resolve().parents[1]
           / "testing" / "live_test" / "l2c_oco_execution.py")

#: The input's ``minval`` is 0.01, so that is the smallest a user can set and the closest
#: the expression can come to changing sign. The rest span both planned runs (0.05 run A,
#: 0.3 run B) and beyond, so a future re-tune cannot quietly leave the pinned range.
SL_VALUES = (0.01, 0.05, 0.2, 0.3, 0.5, 1.0, 5.0)

_ASSIGNMENT = re.compile(r"^\s*DOUBLE_CHECK_PCT\s*=\s*(.+?)\s*$", re.MULTILINE)


def _generated_expression() -> str:
    """The right-hand side of the backstop assignment, from the GENERATED file.

    Raises rather than returning a default when the line is missing: an absent
    assignment must fail this test loudly, not pass it vacuously. A pin that greps
    for something and silently accepts zero matches asserts nothing at all.
    """
    assert VEHICLE.exists(), f"generated vehicle not found: {VEHICLE}"
    matches = _ASSIGNMENT.findall(VEHICLE.read_text())
    assert len(matches) == 1, (
        f"expected exactly one DOUBLE_CHECK_PCT assignment in {VEHICLE.name}, "
        f"found {len(matches)}: {matches!r}"
    )
    return matches[0]


def _evaluate(expression: str, sl_pct: float) -> float:
    return eval(expression, {"__builtins__": {}}, {"slPct": sl_pct})  # noqa: S307


def __test_backstop_threshold_is_negative_for_every_settable_sl__():
    """The shipped vehicle: strictly negative across the whole input range."""
    expression = _generated_expression()
    for sl_pct in SL_VALUES:
        value = _evaluate(expression, sl_pct)
        assert value < 0.0, (
            f"backstop threshold is {value} at slPct={sl_pct} in the GENERATED "
            f"{VEHICLE.name} (expression: {expression!r}). A non-negative threshold "
            f"inverts `openPnlPct < DOUBLE_CHECK_PCT` and fires on the first bar of "
            f"every position."
        )


def __test_backstop_sits_outside_the_stop_leg__():
    """It must be WIDER than the stop it backs up, or it pre-empts a working stop.

    Distinct from the sign check: a threshold of -0.01 is negative and still useless,
    because it would fire before a 0.05 stop could ever trigger.
    """
    expression = _generated_expression()
    for sl_pct in SL_VALUES:
        value = _evaluate(expression, sl_pct)
        assert value < -sl_pct, (
            f"backstop {value} is not outside the stop leg -{sl_pct}; it would fire "
            f"before the stop could trigger and pre-empt the measurement"
        )


@pytest.mark.parametrize("broken", ["-slPct + 0.25", "0.0 - slPct + 0.25"])
def __test_the_pin_catches_the_real_historical_bug__(broken):
    """RED-FIRST, against the exact strings pine2pyne produced on 2026-09-18.

    These are not hypothetical mutants. Both were generated by the transpiler from
    parenthesised Pine source and both evaluate to +0.20 at the run A setting. If this
    test ever passes, the pin above has stopped discriminating and is decorative.
    """
    value = _evaluate(broken, 0.05)
    assert value > 0.0, f"expected the historical broken form to be positive, got {value}"
    assert not value < 0.0, "the sign assertion would have passed the broken form"
