from ...core.callable_module import CallableModule
from ...types.na import NA

class OpenTradesModule(CallableModule, int):
    def __call__(self) -> int: ...

    def new(self): ...

    @property
    def capital_held(self) -> float: ...

    #
    # Functions
    #

    def commission(self, trade_num: int) -> float | NA[float]: ...

    def entry_bar_index(self, trade_num: int) -> int | NA[int]: ...

    def entry_comment(self, trade_num: int) -> str | NA[str]: ...

    def entry_id(self, trade_num: int) -> str | NA[str]: ...

    def entry_price(self, trade_num: int) -> float | NA[float]: ...

    def entry_time(self, trade_num: int) -> int | NA[int]: ...

    def max_drawdown(self, trade_num: int) -> float | NA[float]: ...

    def max_drawdown_percent(self, trade_num: int) -> float | NA[float]: ...

    def max_runup(self, trade_num: int) -> float | NA[float]: ...

    def max_runup_percent(self, trade_num: int) -> float | NA[float]: ...

    def profit(self, trade_num: int) -> float | NA[float]: ...

    def profit_percent(self, trade_num: int) -> float | NA[float]: ...

    def size(self, trade_num: int) -> float | NA[float]: ...


# Module-level declarations (Pylance sees strategy.opentrades as this module)
capital_held: float

def commission(trade_num: int) -> float | NA[float]: ...
def entry_bar_index(trade_num: int) -> int | NA[int]: ...
def entry_comment(trade_num: int) -> str | NA[str]: ...
def entry_id(trade_num: int) -> str | NA[str]: ...
def entry_price(trade_num: int) -> float | NA[float]: ...
def entry_time(trade_num: int) -> int | NA[int]: ...
def max_drawdown(trade_num: int) -> float | NA[float]: ...
def max_drawdown_percent(trade_num: int) -> float | NA[float]: ...
def max_runup(trade_num: int) -> float | NA[float]: ...
def max_runup_percent(trade_num: int) -> float | NA[float]: ...
def profit(trade_num: int) -> float | NA[float]: ...
def profit_percent(trade_num: int) -> float | NA[float]: ...
def size(trade_num: int) -> float | NA[float]: ...

opentrades: OpenTradesModule
